### ISSUE TITLE
unfollowUser issue

### ISSUE THREAD

**Issue by alifnaufalyasin** [osyduck/UnOfficial-Spotify-API#2]
i think in this line is the wrong url or any config, because its same with followUser function, and still following not unfollow the user. 

https://github.com/osyduck/UnOfficial-Spotify-API/blob/c1882c2438533a26f1145df4f72386995430dd0d/function.php#L136

**Comment by osyduck** [comment]
I've fixed this issue. Correct http method for unfollow user must be DELETE not PUT. Thanks for pointing out.
